version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: payload
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data

  setup-bucket:
    depends_on:
      - minio
    image: minio/mc:latest
    entrypoint: >
      /bin/sh -c " /usr/bin/mc alias set local http://minio:9000 minioadmin minioadmin; /usr/bin/mc mb local/leonardstruck exit 0; "

volumes:
  db-data:
  minio-data:
